#!/usr/bin/env bash

URL="https://developers.google.com/android/images"
URLCONTENT=$(curl $URL)
DEVICES="crosshatch blueline taimen walleye marlin sailfish ryu angler bullhead"

# fetch ALL build id's of all devices, and check if there is a new one
build_id() {
    BUILDID_FILE="./devices/$1/build_ids"
    OLD_BUILDIDS=$(cat $BUILDID_FILE)
    NEW_BUILDIDS=$(echo "$URLCONTENT" | sed -n 's/<tr id="'"$1"'//p' | sed -n 's/">//p' | cut -d ' ' -f 3)
    if [[ "$OLD_BUILDIDS" != "$NEW_BUILDIDS" && -n "$NEW_BUILDIDS" ]]; then
        NEW_BUILDID=$(diff -u <(echo "$NEW_BUILDIDS") <(echo "$OLD_BUILDIDS") | sed -n '1!p' | sed -n 's/^-//p')
        NEW_BUILDURL=$(echo "$URLCONTENT" |grep $1 | grep $NEW_BUILDID | grep https| sed -n 's/<td><a href="//;s/"//p' | tr -d ' ')
        echo "$NEW_BUILDIDS" > $BUILDID_FILE
    else
        return 1
    fi
}

for device in $DEVICES; do
    if build_id $device; then
        MESSAGE+="*$device*: $NEW_BUILDID has been released.%0A    - Factory image: [Download]($NEW_BUILDURL)"
    fi
done

if [[ -n $MESSAGE ]]; then
    tg_bot -p pm -m "$MESSAGE"
fi
