#!/usr/bin/env bash

TOKEN=791403579:AAHwmaSLni3OK3yIBZY1OVFr3Uo568s6K8k
CHAT_ID="-1001424244499"
MESSAGE="$1"
URL="https://api.telegram.org/bot$TOKEN/sendMessage"

for i in "${CHAT_ID[@]}"; do
    curl -s -X POST $URL -d chat_id=$i -d text="$MESSAGE"
done
